// Build version: 131660
const hero_localize = {
  "Рокара": "Rokara",
  "Rokara": "Rokara",
  "洛卡拉": "Rokara",
  "洛卡菈": "Rokara",
  "ロカラ": "Rokara",
  "Зирелла": "Xyrella",
  "Xyrella": "Xyrella",
  "泽瑞拉": "Xyrella",
  "賽瑞菈": "Xyrella",
  "ザイレラ": "Xyrella",
  "Воевода Саурфанг": "Overlord Saurfang",
  "Señor supremo Colmillosauro": "Overlord Saurfang",
  "Seigneur Saurcroc": "Overlord Saurfang",
  "萨鲁法尔大王": "Overlord Saurfang",
  "薩魯法爾霸王": "Overlord Saurfang",
  "Hochfürst Saurfang": "Overlord Saurfang",
  "Supremo Faucisaure": "Overlord Saurfang",
  "サウルファング元帥": "Overlord Saurfang",
  "Вестник смерти Черношип": "Death Speaker Blackthorn",
  "Portavoz de muerte Espina Negra": "Death Speaker Blackthorn",
  "Portavoz de la muerte Espina Negra": "Death Speaker Blackthorn",
  "Nécrorateur Noirépine": "Death Speaker Blackthorn",
  "亡语者布莱克松": "Death Speaker Blackthorn",
  "亡語者黑棘": "Death Speaker Blackthorn",
  "Todessprecher Schwarzdorn": "Death Speaker Blackthorn",
  "Oratore della Morte Spinanera": "Death Speaker Blackthorn",
  "死の説教師ブラックソーン": "Death Speaker Blackthorn",
  "Вол'джин": "Vol'jin",
  "Vol'jin": "Vol'jin",
  "Vol’jin": "Vol'jin",
  "沃金": "Vol'jin",
  "ヴォルジン": "Vol'jin",
  "Мастер Нгуен": "Master Nguyen",
  "Maestro Nguyen": "Master Nguyen",
  "Maître Nguyen": "Master Nguyen",
  "阮大师": "Master Nguyen",
  "阮大師": "Master Nguyen",
  "Meister Nguyen": "Master Nguyen",
  "マスター・ウェン": "Master Nguyen",
  "Гафф Рунический Тотем": "Guff Runetotem",
  "Guff Tótem de Runa": "Guff Runetotem",
  "Guff Totem-Runique": "Guff Runetotem",
  "古夫·符文图腾": "Guff Runetotem",
  "葛夫‧符文圖騰": "Guff Runetotem",
  "Guff Runentotem": "Guff Runetotem",
  "Guff Totem Runico": "Guff Runetotem",
  "ガフ・ルーントーテム": "Guff Runetotem",
  "Куртрус Ливень Пепла": "Kurtrus Ashfallen",
  "Kurtrus Cinéreo": "Kurtrus Ashfallen",
  "Kurtrus Cenizacaída": "Kurtrus Ashfallen",
  "Kurtrus Chutecendre": "Kurtrus Ashfallen",
  "库尔特鲁斯·陨烬": "Kurtrus Ashfallen",
  "克圖斯‧灰殞": "Kurtrus Ashfallen",
  "Kurtrus Aschensturz": "Kurtrus Ashfallen",
  "Kurtrus Domacenere": "Kurtrus Ashfallen",
  "カートラス・アッシュフォールン": "Kurtrus Ashfallen",
  "Тамсин Роум": "Tamsin Roame",
  "Tamsin Roame": "Tamsin Roame",
  "塔姆辛·罗姆": "Tamsin Roame",
  "塔姆辛‧羅姆": "Tamsin Roame",
  "タムシン・ローム": "Tamsin Roame",
  "Бурекрыл": "Galewing",
  "Alavento": "Galewing",
  "Alavendaval": "Galewing",
  "Bec-au-vent": "Galewing",
  "狂风之翼": "Galewing",
  "飆翼": "Galewing",
  "Sturmschwinge": "Galewing",
  "ゲイルウィング": "Galewing",
  "Мутанус Пожиратель": "Mutanus the Devourer",
  "Mutanus el Devorador": "Mutanus the Devourer",
  "Mutanus le Dévoreur": "Mutanus the Devourer",
  "吞噬者穆坦努斯": "Mutanus the Devourer",
  "Mutanus der Verschlinger": "Mutanus the Devourer",
  "Mutanus il Divoratore": "Mutanus the Devourer",
  "貪り喰らうものミュターヌス": "Mutanus the Devourer",
  "Кариэль Роум": "Cariel Roame",
  "Cariel Roame": "Cariel Roame",
  "凯瑞尔·罗姆": "Cariel Roame",
  "凱瑞爾‧羅姆": "Cariel Roame",
  "キャリエル・ローム": "Cariel Roame",
  "Скаббс Маслорез": "Scabbs Cutterbutter",
  "Scabbs Cortamanteca": "Scabbs Cutterbutter",
  "Tchak Coupebeurre": "Scabbs Cutterbutter",
  "斯卡布斯·刀油": "Scabbs Cutterbutter",
  "史蓋伯斯‧油切": "Scabbs Cutterbutter",
  "Schnipps Butterbeil": "Scabbs Cutterbutter",
  "Scabb Tranciaburro": "Scabbs Cutterbutter",
  "スキャブス・カッターバター": "Scabbs Cutterbutter",
  "Кок Пирожок": "Cookie the Cook",
  "Cocinitas, el Cocinero": "Cookie the Cook",
  "Cocinitas el cocinero": "Cookie the Cook",
  "Macaron le cuisinier": "Cookie the Cook",
  "厨师曲奇": "Cookie the Cook",
  "餅乾大廚": "Cookie the Cook",
  "Krümel der Smutje": "Cookie the Cook",
  "Dolcetto il Cuoco": "Cookie the Cook",
  "コックのクッキー": "Cookie the Cook",
  "Снид": "Sneed",
  "Sneed": "Sneed",
  "斯尼德": "Sneed",
  "スニード": "Sneed",
  "Тавиш Грозовая Вершина": "Tavish Stormpike",
  "Tavish Pico Tormenta": "Tavish Stormpike",
  "Tavish Foudrepique": "Tavish Stormpike",
  "塔维什·雷矛": "Tavish Stormpike",
  "塔維西‧雷矛": "Tavish Stormpike",
  "Tavish Sturmlanze": "Tavish Stormpike",
  "Tavish Piccatonante": "Tavish Stormpike",
  "タヴィッシュ・ストームパイク": "Tavish Stormpike",
  "Бру'кан": "Bru'kan",
  "Bru'kan": "Bru'kan",
  "Bru’kan": "Bru'kan",
  "布鲁坎": "Bru'kan",
  "布魯坎": "Bru'kan",
  "ブルカン": "Bru'kan",
  "Дрек'Тар": "Drek'Thar",
  "Drek'Thar": "Drek'Thar",
  "Drek’Thar": "Drek'Thar",
  "德雷克塔尔": "Drek'Thar",
  "德雷克塔爾": "Drek'Thar",
  "Drek'thar": "Drek'Thar",
  "ドレクサー": "Drek'Thar",
  "Вандар Грозовая Вершина": "Vanndar Stormpike",
  "Vanndar Pico Tormenta": "Vanndar Stormpike",
  "Vanndar Foudrepique": "Vanndar Stormpike",
  "范达尔·雷矛": "Vanndar Stormpike",
  "范達爾·雷矛": "Vanndar Stormpike",
  "Vanndar Sturmlanze": "Vanndar Stormpike",
  "Vanndar Piccatonante": "Vanndar Stormpike",
  "ヴァンダル・ストームパイク": "Vanndar Stormpike",
  "Варден Луч Рассвета": "Varden Dawngrasp",
  "Varden Albaciernes": "Varden Dawngrasp",
  "Varden Aferralba": "Varden Dawngrasp",
  "Varden Aubétreinte": "Varden Dawngrasp",
  "瓦尔登·晨拥": "Varden Dawngrasp",
  "瓦登‧晨握": "Varden Dawngrasp",
  "Varden Dämmergriff": "Varden Dawngrasp",
  "Varden Ghermiluce": "Varden Dawngrasp",
  "ヴァーデン・ドーングラスプ": "Varden Dawngrasp",
  "Ониксия": "Onyxia",
  "Onyxia": "Onyxia",
  "奥妮克希亚": "Onyxia",
  "奧妮克希亞": "Onyxia",
  "オニクシア": "Onyxia",
  "Эдвин ван Клиф": "Edwin VanCleef",
  "Edwin VanCleef": "Edwin VanCleef",
  "艾德温·范克里夫": "Edwin VanCleef",
  "艾德溫‧范克里夫": "Edwin VanCleef",
  "Edwin van Cleef": "Edwin VanCleef",
  "エドウィン・ヴァンクリーフ": "Edwin VanCleef",
  "Галакронд": "Galakrond",
  "Galakrond": "Galakrond",
  "迦拉克隆": "Galakrond",
  "葛拉克朗": "Galakrond",
  "ガラクロンド": "Galakrond",
  "Иллидан": "Illidan Stormrage",
  "Illidan Tempestira": "Illidan Stormrage",
  "Illidan Hurlorage": "Illidan Stormrage",
  "伊利丹·怒风": "Illidan Stormrage",
  "伊利丹‧怒風": "Illidan Stormrage",
  "Illidan Sturmgrimm": "Illidan Stormrage",
  "Illidan Grantempesta": "Illidan Stormrage",
  "イリダン・ストームレイジ": "Illidan Stormrage",
  "Принц Галливикс": "Trade Prince Gallywix",
  "Príncipe mercante Gallywix": "Trade Prince Gallywix",
  "Prince marchand Gallywix": "Trade Prince Gallywix",
  "贸易大王加里维克斯": "Trade Prince Gallywix",
  "貿易親王加里維克斯": "Trade Prince Gallywix",
  "Handelsprinz Gallywix": "Trade Prince Gallywix",
  "Principe Gallywix": "Trade Prince Gallywix",
  "商大公ガリーウィックス": "Trade Prince Gallywix",
  "Рагнарос": "Ragnaros the Firelord",
  "Ragnaros, el Señor del Fuego": "Ragnaros the Firelord",
  "Ragnaros, Señor del Fuego": "Ragnaros the Firelord",
  "Ragnaros, seigneur du feu": "Ragnaros the Firelord",
  "炎魔之王拉格纳罗斯": "Ragnaros the Firelord",
  "『炎魔』拉格納羅斯": "Ragnaros the Firelord",
  "Ragnaros der Feuerfürst": "Ragnaros the Firelord",
  "Ragnaros": "Ragnaros the Firelord",
  "炎の王ラグナロス": "Ragnaros the Firelord",
  "Крысиный король": "The Rat King",
  "El Rey Rata": "The Rat King",
  "Rey de las ratas": "The Rat King",
  "Le roi des rats": "The Rat King",
  "鼠王": "The Rat King",
  "老鼠王": "The Rat King",
  "Der Rattenkönig": "The Rat King",
  "Re dei Ratti": "The Rat King",
  "ネズミの王": "The Rat King",
  "Королева Пыхлевих": "Queen Wagtoggle",
  "Reina Wagtoggle": "Queen Wagtoggle",
  "Reina Flojatoga": "Queen Wagtoggle",
  "Souveraine Cire-Reine": "Queen Wagtoggle",
  "瓦托格尔女王": "Queen Wagtoggle",
  "瓦哥托戈女王": "Queen Wagtoggle",
  "Königin Wagtoggel": "Queen Wagtoggle",
  "Regina Cobalda": "Queen Wagtoggle",
  "ワグトグル女王": "Queen Wagtoggle",
  "Джордж Падший": "George the Fallen",
  "George el Caído": "George the Fallen",
  "George le Déchu": "George the Fallen",
  "堕落的乔治": "George the Fallen",
  "墮落的喬治": "George the Fallen",
  "Gustav der Gefallene": "George the Fallen",
  "Paolo il Caduto": "George the Fallen",
  "地獄のジョージ": "George the Fallen",
  "А. Ф. Ка": "A. F. Kay",
  "Au Sente": "A. F. Kay",
  "A. F. Ka": "A. F. Kay",
  "A. F. Kah": "A. F. Kay",
  "挂机的阿凯": "A. F. Kay",
  "詹莉‧伊夏": "A. F. Kay",
  "A. F. Karla": "A. F. Kay",
  "A. F. Kappa": "A. F. Kay",
  "A. F. ケイ": "A. F. Kay",
  "Миллифисент Манашторм": "Millificent Manastorm",
  "Maleficia Tormenta de Maná": "Millificent Manastorm",
  "Malífica Tormenta de Maná": "Millificent Manastorm",
  "Millificent Tempête-de-Mana": "Millificent Manastorm",
  "米尔菲丝·法力风暴": "Millificent Manastorm",
  "米歐菲瑟‧曼納斯頓": "Millificent Manastorm",
  "Millificent Manasturm": "Millificent Manastorm",
  "Millefica Manalampo": "Millificent Manastorm",
  "ミリフィセント・マナストーム": "Millificent Manastorm",
  "Пират Глазастик": "Patches the Pirate",
  "Parches el Pirata": "Patches the Pirate",
  "Neunœil le pirate": "Patches the Pirate",
  "海盗帕奇斯": "Patches the Pirate",
  "海盜派奇": "Patches the Pirate",
  "Käpt’n Glubschauge": "Patches the Pirate",
  "Sghigno il Pirata": "Patches the Pirate",
  "海賊パッチーズ": "Patches the Pirate",
  "Ахалаймахалай": "The Great Akazamzarak",
  "El Gran Akazamzarak": "The Great Akazamzarak",
  "Le grand Akazamzarak": "The Great Akazamzarak",
  "伟大的阿卡扎曼扎拉克": "The Great Akazamzarak",
  "魔術大師阿卡贊札拉克": "The Great Akazamzarak",
  "Der Große Akazamzarak": "The Great Akazamzarak",
  "Akazamzarak il Grande": "The Great Akazamzarak",
  "偉大なるアカザムザラク": "The Great Akazamzarak",
  "Король-лич": "The Lich King",
  "El Rey Exánime": "The Lich King",
  "Le roi-liche": "The Lich King",
  "巫妖王": "The Lich King",
  "Der Lichkönig": "The Lich King",
  "Re dei Lich": "The Lich King",
  "リッチキング": "The Lich King",
  "Дрыжеглот": "Shudderwock",
  "Shudderwock": "Shudderwock",
  "Espantagón": "Shudderwock",
  "Carniflore": "Shudderwock",
  "沙德沃克": "Shudderwock",
  "哮斗龍": "Shudderwock",
  "Der Grauselhurz": "Shudderwock",
  "Ciciazampa": "Shudderwock",
  "シャダウォック": "Shudderwock",
  "Лич Баз'хиал": "Lich Baz'hial",
  "Exánime Baz'hial": "Lich Baz'hial",
  "Baz’hial la liche": "Lich Baz'hial",
  "巫妖巴兹亚尔": "Lich Baz'hial",
  "巫妖拜茲希爾": "Lich Baz'hial",
  "Lich Baz’hial": "Lich Baz'hial",
  "Lich Baz'hial": "Lich Baz'hial",
  "リッチのバズィアル": "Lich Baz'hial",
  "Синдрагоса": "Sindragosa",
  "Sindragosa": "Sindragosa",
  "辛达苟萨": "Sindragosa",
  "辛德拉苟莎": "Sindragosa",
  "シンドラゴサ": "Sindragosa",
  "Вечная Токи": "Infinite Toki",
  "Toki infinita": "Infinite Toki",
  "Toki la Infinita": "Infinite Toki",
  "Toki l’Infinie": "Infinite Toki",
  "永恒者托奇": "Infinite Toki",
  "無限托奇": "Infinite Toki",
  "Toki die Unendliche": "Infinite Toki",
  "Toki dell'Infinito": "Infinite Toki",
  "無限のトキ": "Infinite Toki",
  "К'Тун": "C'Thun",
  "C'Thun": "C'Thun",
  "C’Thun": "C'Thun",
  "克苏恩": "C'Thun",
  "克蘇恩": "C'Thun",
  "C'thun": "C'Thun",
  "クトゥーン": "C'Thun",
  "Смотритель": "The Curator",
  "El Curator": "The Curator",
  "Le conservateur": "The Curator",
  "馆长": "The Curator",
  "館長": "The Curator",
  "Der Kurator": "The Curator",
  "Curatore": "The Curator",
  "キュレーター": "The Curator",
  "Лоскутик": "Patchwerk",
  "Remendejo": "Patchwerk",
  "Le Recousu": "Patchwerk",
  "帕奇维克": "Patchwerk",
  "縫補者": "Patchwerk",
  "Flickwerk": "Patchwerk",
  "Pezzacarne": "Patchwerk",
  "パッチウァーク": "Patchwerk",
  "Йогг-Сарон": "Yogg-Saron, Hope's End",
  "Yogg-Saron, Fin de la esperanza": "Yogg-Saron, Hope's End",
  "Yogg-Saron, Fin de la Esperanza": "Yogg-Saron, Hope's End",
  "Yogg-Saron, la fin de l’espoir": "Yogg-Saron, Hope's End",
  "尤格-萨隆": "Yogg-Saron, Hope's End",
  "『深沉絕望』尤格薩倫": "Yogg-Saron, Hope's End",
  "Yogg-Saron, Hoffnungsende": "Yogg-Saron, Hope's End",
  "Yogg-Saron": "Yogg-Saron, Hope's End",
  "希望の終焉ヨグ＝サロン": "Yogg-Saron, Hope's End",
  "Танцор Дэрил": "Dancin' Deryl",
  "Daryl Danzarín": "Dancin' Deryl",
  "Daryl el Bailarín": "Dancin' Deryl",
  "Daryl le Danseur": "Dancin' Deryl",
  "舞者达瑞尔": "Dancin' Deryl",
  "跳舞的戴瑞": "Dancin' Deryl",
  "Der steppende Steppke": "Dancin' Deryl",
  "Sfrl lo Sfrenato": "Dancin' Deryl",
  "ダンシン・ダリル": "Dancin' Deryl",
  "Лорд Джараксус": "Lord Jaraxxus",
  "Lord Jaraxxus": "Lord Jaraxxus",
  "Seigneur Jaraxxus": "Lord Jaraxxus",
  "加拉克苏斯大王": "Lord Jaraxxus",
  "賈拉克瑟斯領主": "Lord Jaraxxus",
  "Sire Jaraxxus": "Lord Jaraxxus",
  "ロード・ジャラクサス": "Lord Jaraxxus",
  "Король Мукла": "King Mukla",
  "Rey Mukla": "King Mukla",
  "Roi Mukla": "King Mukla",
  "穆克拉": "King Mukla",
  "König Mukla": "King Mukla",
  "Re Mukla": "King Mukla",
  "キング・ムクラ": "King Mukla",
  "Пирамидон": "Pyramad",
  "Pyramad": "Pyramad",
  "Piramido": "Pyramad",
  "Pyraride": "Pyramad",
  "疯狂金字塔": "Pyramad",
  "瘋狂金字塔": "Pyramad",
  "Pyramidos": "Pyramad",
  "Piramatta": "Pyramad",
  "ピラマッド": "Pyramad",
  "Сэр Финли Мрргглтон": "Sir Finley Mrrgglton",
  "Sir Aletardo Mrrgglton": "Sir Finley Mrrgglton",
  "Sir Finley Mrrgglton": "Sir Finley Mrrgglton",
  "芬利·莫格顿爵士": "Sir Finley Mrrgglton",
  "芬利‧莫戈頓爵士": "Sir Finley Mrrgglton",
  "Ser Pinnus Mrrgglton": "Sir Finley Mrrgglton",
  "サー・フィンレー・マルグルトン": "Sir Finley Mrrgglton",
  "Рено Джексон": "Reno Jackson",
  "Reno Jackson": "Reno Jackson",
  "雷诺·杰克逊": "Reno Jackson",
  "里諾‧傑克森": "Reno Jackson",
  "レノ・ジャクソン": "Reno Jackson",
  "Элиза Звездочет": "Elise Starseeker",
  "Elisa Buscaestelar": "Elise Starseeker",
  "Elise Buscaestelar": "Elise Starseeker",
  "Élise Cherchétoile": "Elise Starseeker",
  "伊莉斯·逐星": "Elise Starseeker",
  "伊莉絲‧尋星者": "Elise Starseeker",
  "Elise Sternensucher": "Elise Starseeker",
  "Elise Cercastelle": "Elise Starseeker",
  "エリーズ・スターシーカー": "Elise Starseeker",
  "Укротитель ящеров Бранн": "Dinotamer Brann",
  "Domadinos Brann": "Dinotamer Brann",
  "Dinodompteur Brann": "Dinotamer Brann",
  "恐龙大师布莱恩": "Dinotamer Brann",
  "恐龍馴服者布萊恩": "Dinotamer Brann",
  "Brann der Dinozähmer": "Dinotamer Brann",
  "Domasauri Brann": "Dinotamer Brann",
  "恐竜使いブラン": "Dinotamer Brann",
  "Суперзлодей Рафаам": "Arch-Villain Rafaam",
  "Archivillano Rafaam": "Arch-Villain Rafaam",
  "Prince du mal Rafaam": "Arch-Villain Rafaam",
  "至尊盗王拉法姆": "Arch-Villain Rafaam",
  "極盜天王拉法姆": "Arch-Villain Rafaam",
  "Erzschurke Rafaam": "Arch-Villain Rafaam",
  "Arcicattivo Rafaam": "Arch-Villain Rafaam",
  "大悪党ラファーム": "Arch-Villain Rafaam",
  "Миллхаус Манашторм": "Millhouse Manastorm",
  "Molino Tormenta de Maná": "Millhouse Manastorm",
  "Millhouse Tempête-de-Mana": "Millhouse Manastorm",
  "米尔豪斯·法力风暴": "Millhouse Manastorm",
  "米歐浩斯‧曼納斯頓": "Millhouse Manastorm",
  "Millhaus Manasturm": "Millhouse Manastorm",
  "Millhouse Manalampo": "Millhouse Manastorm",
  "ミルハウス・マナストーム": "Millhouse Manastorm",
  "Тесс Седогрив": "Tess Greymane",
  "Tess Cringris": "Tess Greymane",
  "Tess Cringrís": "Tess Greymane",
  "Tess Grisetête": "Tess Greymane",
  "苔丝·格雷迈恩": "Tess Greymane",
  "泰絲‧葛雷邁恩": "Tess Greymane",
  "Tess Graumähne": "Tess Greymane",
  "Tess Mantogrigio": "Tess Greymane",
  "テス・グレイメイン": "Tess Greymane",
  "Смертокрыл": "Deathwing",
  "Alamuerte": "Deathwing",
  "Aile de mort": "Deathwing",
  "死亡之翼": "Deathwing",
  "Todesschwinge": "Deathwing",
  "Alamorte": "Deathwing",
  "デスウィング": "Deathwing",
  "Изера": "Ysera",
  "Ysera": "Ysera",
  "伊瑟拉": "Ysera",
  "イセラ": "Ysera",
  "Грибомант Флургл": "Fungalmancer Flurgl",
  "Fungimántico Flurgl": "Fungalmancer Flurgl",
  "Fongimancien Flurgl": "Fungalmancer Flurgl",
  "菌菇术士弗洛格尔": "Fungalmancer Flurgl",
  "真菌術師弗勒戈": "Fungalmancer Flurgl",
  "Fungumant Flrrgl": "Fungalmancer Flurgl",
  "Fungomante Flurgl": "Fungalmancer Flurgl",
  "菌術師フラァグル": "Fungalmancer Flurgl",
  "Алекстраза": "Alexstrasza",
  "Alexstrasza": "Alexstrasza",
  "阿莱克丝塔萨": "Alexstrasza",
  "雅立史卓莎": "Alexstrasza",
  "アレクストラーザ": "Alexstrasza",
  "Ноздорму": "Nozdormu",
  "Nozdormu": "Nozdormu",
  "诺兹多姆": "Nozdormu",
  "諾茲多姆": "Nozdormu",
  "ノズドルム": "Nozdormu",
  "Малигос": "Malygos",
  "Malygos": "Malygos",
  "玛里苟斯": "Malygos",
  "瑪里苟斯": "Malygos",
  "マリゴス": "Malygos",
  "Аранна Звездочет": "Aranna Starseeker",
  "Aranna Buscaestelar": "Aranna Starseeker",
  "Aranna Cherchétoile": "Aranna Starseeker",
  "阿兰娜·逐星": "Aranna Starseeker",
  "艾蘭娜‧尋星者": "Aranna Starseeker",
  "Aranna Sternensucher": "Aranna Starseeker",
  "Aranna Cercastelle": "Aranna Starseeker",
  "アランナ・スターシーカー": "Aranna Starseeker",
  "Принц Кель'тас": "Kael'thas Sunstrider",
  "Kael'thas Caminante del Sol": "Kael'thas Sunstrider",
  "Kael’thas Haut-Soleil": "Kael'thas Sunstrider",
  "凯尔萨斯·逐日者": "Kael'thas Sunstrider",
  "凱爾薩斯‧逐日者": "Kael'thas Sunstrider",
  "Kael’thas Sonnenwanderer": "Kael'thas Sunstrider",
  "Kael'thas Solealto": "Kael'thas Sunstrider",
  "ケルサス・サンストライダー": "Kael'thas Sunstrider",
  "Майев Песнь Теней": "Maiev Shadowsong",
  "Maiev Cantosombrío": "Maiev Shadowsong",
  "Maiev Chantelombre": "Maiev Shadowsong",
  "玛维·影歌": "Maiev Shadowsong",
  "瑪翼夫‧影歌": "Maiev Shadowsong",
  "Maiev Schattensang": "Maiev Shadowsong",
  "Maiev Cantombroso": "Maiev Shadowsong",
  "マイエヴ・シャドウソング": "Maiev Shadowsong",
  "Капитан Юдора": "Captain Eudora",
  "Capitana Eudora": "Captain Eudora",
  "Capitaine Eudora": "Captain Eudora",
  "尤朵拉船长": "Captain Eudora",
  "尤多拉船長": "Captain Eudora",
  "Käpt’n Eudora": "Captain Eudora",
  "Capitano Eudora": "Captain Eudora",
  "ユードラ船長": "Captain Eudora",
  "Капитан Кривоклык": "Captain Hooktusk",
  "Capitana Colmigarfio": "Captain Hooktusk",
  "Capitaine Double-Crochet": "Captain Hooktusk",
  "钩牙船长": "Captain Hooktusk",
  "鉤牙船長": "Captain Hooktusk",
  "Käpt’n Haizahn": "Captain Hooktusk",
  "Capitan Zannuncino": "Captain Hooktusk",
  "フックタスク船長": "Captain Hooktusk",
  "Крагг Поднебесный": "Skycap'n Kragg",
  "Capitán celestial Kragg": "Skycap'n Kragg",
  "Capitán de los cielos Kragg": "Skycap'n Kragg",
  "Cap’taine céleste Kragg": "Skycap'n Kragg",
  "天空上尉库拉格": "Skycap'n Kragg",
  "天空隊長克拉格": "Skycap'n Kragg",
  "Himmelskäpt’n Kragg": "Skycap'n Kragg",
  "Gran Capitano Kragg": "Skycap'n Kragg",
  "空賊船長クラッグ": "Skycap'n Kragg",
  "Мистер Бигглсуорт": "Mr. Bigglesworth",
  "Baldomero": "Mr. Bigglesworth",
  "M. Bigglesworth": "Mr. Bigglesworth",
  "比格沃斯先生": "Mr. Bigglesworth",
  "畢勾沃斯先生": "Mr. Bigglesworth",
  "Mr. Bigglesworth": "Mr. Bigglesworth",
  "Signor Bigolo": "Mr. Bigglesworth",
  "ビグルスワース君": "Mr. Bigglesworth",
  "Джандис Барова": "Jandice Barov",
  "Jandice Barov": "Jandice Barov",
  "詹迪斯·巴罗夫": "Jandice Barov",
  "詹迪斯‧巴羅夫": "Jandice Barov",
  "ジャンディス・バロフ": "Jandice Barov",
  "Лорд Баров": "Lord Barov",
  "Lord Barov": "Lord Barov",
  "Seigneur Barov": "Lord Barov",
  "巴罗夫领主": "Lord Barov",
  "巴羅夫領主": "Lord Barov",
  "Ser Barov": "Lord Barov",
  "ロード・バロフ": "Lord Barov",
  "Страж леса Ому": "Forest Warden Omu",
  "Guardiana del bosque Omu": "Forest Warden Omu",
  "Omu, celadora del bosque": "Forest Warden Omu",
  "Gardienne de la forêt Omu": "Forest Warden Omu",
  "林地守护者欧穆": "Forest Warden Omu",
  "森林看守者歐穆": "Forest Warden Omu",
  "Waldwächterin Omu": "Forest Warden Omu",
  "Guardiana Omu": "Forest Warden Omu",
  "森番オム": "Forest Warden Omu",
  "Раканишу": "Rakanishu",
  "Rakanishu": "Rakanishu",
  "拉卡尼休": "Rakanishu",
  "ラカニシュ": "Rakanishu",
  "Ал'акир": "Al'Akir",
  "Al'Akir": "Al'Akir",
  "Al’Akir": "Al'Akir",
  "奥拉基尔": "Al'Akir",
  "奧拉基爾": "Al'Akir",
  "アラキア": "Al'Akir",
  "Нави'ла": "Chenvaala",
  "Chenvaala": "Chenvaala",
  "Chenvaa’la": "Chenvaala",
  "齐恩瓦拉": "Chenvaala",
  "泫瓦拉": "Chenvaala",
  "シェンヴァーラ": "Chenvaala",
  "Сайлас Новолуний": "Silas Darkmoon",
  "Silas Luna Negra": "Silas Darkmoon",
  "Silas Sombrelune": "Silas Darkmoon",
  "希拉斯·暗月": "Silas Darkmoon",
  "希拉斯‧暗月": "Silas Darkmoon",
  "Silas Dunkelmond": "Silas Darkmoon",
  "Silas Lunacupa": "Silas Darkmoon",
  "サイラス・ダークムーン": "Silas Darkmoon",
  "Зефрис Великий": "Zephrys, the Great",
  "El Gran Zephrys": "Zephrys, the Great",
  "Zephrys el Grande": "Zephrys, the Great",
  "Zéphrys le Grand": "Zephrys, the Great",
  "了不起的杰弗里斯": "Zephrys, the Great",
  "偉大的賽佛瑞斯": "Zephrys, the Great",
  "Zephrys der Große": "Zephrys, the Great",
  "Zefris il Grande": "Zephrys, the Great",
  "偉大なるゼフリス": "Zephrys, the Great",
  "И'Шарадж": "Y'Shaarj",
  "Y'shaarj": "Y'Shaarj",
  "Y'Shaarj": "Y'Shaarj",
  "Y’Shaarj": "Y'Shaarj",
  "亚煞极": "Y'Shaarj",
  "亞煞拉懼": "Y'Shaarj",
  "ヤシャラージュ": "Y'Shaarj",
  "Н'Зот": "N'Zoth",
  "N'Zoth": "N'Zoth",
  "N’Zoth": "N'Zoth",
  "恩佐斯": "N'Zoth",
  "恩若司": "N'Zoth",
  "N'zoth": "N'Zoth",
  "ン＝ゾス": "N'Zoth",
  "Билетикус": "Tickatus",
  "Valestus": "Tickatus",
  "Tiquetus": "Tickatus",
  "Tickatus": "Tickatus",
  "提克特斯": "Tickatus",
  "提卡特斯": "Tickatus",
  "Bigliettus": "Tickatus",
  "チケッタス": "Tickatus",
  "Серокрон": "Greybough",
  "Ramasgrises": "Greybough",
  "Ramagrís": "Greybough",
  "Grisebranche": "Greybough",
  "格雷布": "Greybough",
  "灰枝": "Greybough",
  "Grauzweig": "Greybough",
  "Ramogrigio": "Greybough",
  "Аранна Освобожденная": "Aranna, Unleashed",
  "Aranna, Desatada": "Aranna, Unleashed",
  "Aranna desatada": "Aranna, Unleashed",
  "Aranna, déchaînée": "Aranna, Unleashed",
  "释放自我的阿兰娜": "Aranna, Unleashed",
  "解放的艾蘭娜": "Aranna, Unleashed",
  "Aranna die Entfesselte": "Aranna, Unleashed",
  "Aranna, Inarrestabile": "Aranna, Unleashed",
  "魔解天衝アランナ": "Aranna, Unleashed",
};
export default hero_localize;
