// Build version: 65000
const hero_localize = {
  "Эдвин ван Клиф": "Edwin VanCleef",
  "Edwin VanCleef": "Edwin VanCleef",
  "艾德温·范克里夫": "Edwin VanCleef",
  "Edwin van Cleef": "Edwin VanCleef",
  "Галакронд": "Galakrond",
  "Galakrond": "Galakrond",
  "迦拉克隆": "Galakrond",
  "Иллидан": "Illidan Stormrage",
  "Illidan Tempestira": "Illidan Stormrage",
  "Illidan Hurlorage": "Illidan Stormrage",
  "伊利丹·怒风": "Illidan Stormrage",
  "Illidan Sturmgrimm": "Illidan Stormrage",
  "Illidan Grantempesta": "Illidan Stormrage",
  "Рагнарос": "Ragnaros the Firelord",
  "Ragnaros, el Señor del Fuego": "Ragnaros the Firelord",
  "Ragnaros, Señor del Fuego": "Ragnaros the Firelord",
  "Ragnaros, seigneur du feu": "Ragnaros the Firelord",
  "炎魔之王拉格纳罗斯": "Ragnaros the Firelord",
  "Ragnaros der Feuerfürst": "Ragnaros the Firelord",
  "Ragnaros": "Ragnaros the Firelord",
  "Крысиный король": "The Rat King",
  "El Rey Rata": "The Rat King",
  "Rey de las ratas": "The Rat King",
  "Le roi des rats": "The Rat King",
  "鼠王": "The Rat King",
  "Der Rattenkönig": "The Rat King",
  "Re dei Ratti": "The Rat King",
  "Королева Пыхлевих": "Queen Wagtoggle",
  "Reina Wagtoggle": "Queen Wagtoggle",
  "Reina Flojatoga": "Queen Wagtoggle",
  "Souveraine Cire-Reine": "Queen Wagtoggle",
  "瓦托格尔女王": "Queen Wagtoggle",
  "Königin Wagtoggel": "Queen Wagtoggle",
  "Regina Cobalda": "Queen Wagtoggle",
  "Джордж Падший": "George the Fallen",
  "George el Caído": "George the Fallen",
  "George le Déchu": "George the Fallen",
  "堕落的乔治": "George the Fallen",
  "Gustav der Gefallene": "George the Fallen",
  "Paolo il Caduto": "George the Fallen",
  "А. Ф. Ка": "A. F. Kay",
  "Au Sente": "A. F. Kay",
  "A. F. Ka": "A. F. Kay",
  "A. F. Kah": "A. F. Kay",
  "挂机的阿凯": "A. F. Kay",
  "A. F. Karla": "A. F. Kay",
  "A. F. Kappa": "A. F. Kay",
  "Миллифисент Манашторм": "Millificent Manastorm",
  "Maleficia Tormenta de Maná": "Millificent Manastorm",
  "Malífica Tormenta de Maná": "Millificent Manastorm",
  "Millificent Tempête-de-Mana": "Millificent Manastorm",
  "米尔菲丝·法力风暴": "Millificent Manastorm",
  "Millificent Manasturm": "Millificent Manastorm",
  "Millefica Manalampo": "Millificent Manastorm",
  "Пират Глазастик": "Patches the Pirate",
  "Parches el Pirata": "Patches the Pirate",
  "Neunœil le pirate": "Patches the Pirate",
  "海盗帕奇斯": "Patches the Pirate",
  "Käpt’n Glubschauge": "Patches the Pirate",
  "Sghigno il Pirata": "Patches the Pirate",
  "Ахалаймахалай": "The Great Akazamzarak",
  "El Gran Akazamzarak": "The Great Akazamzarak",
  "Le grand Akazamzarak": "The Great Akazamzarak",
  "伟大的阿卡扎曼扎拉克": "The Great Akazamzarak",
  "Der Große Akazamzarak": "The Great Akazamzarak",
  "Akazamzarak il Grande": "The Great Akazamzarak",
  "Король-лич": "The Lich King",
  "El Rey Exánime": "The Lich King",
  "Le roi-liche": "The Lich King",
  "巫妖王": "The Lich King",
  "Der Lichkönig": "The Lich King",
  "Re dei Lich": "The Lich King",
  "Дрыжеглот": "Shudderwock",
  "Shudderwock": "Shudderwock",
  "Espantagón": "Shudderwock",
  "Carniflore": "Shudderwock",
  "沙德沃克": "Shudderwock",
  "Der Grauselhurz": "Shudderwock",
  "Ciciazampa": "Shudderwock",
  "Лич Баз'хиал": "Lich Baz'hial",
  "Exánime Baz'hial": "Lich Baz'hial",
  "Baz’hial la liche": "Lich Baz'hial",
  "巫妖巴兹亚尔": "Lich Baz'hial",
  "Lich Baz’hial": "Lich Baz'hial",
  "Lich Baz'hial": "Lich Baz'hial",
  "Синдрагоса": "Sindragosa",
  "Sindragosa": "Sindragosa",
  "辛达苟萨": "Sindragosa",
  "Вечная Токи": "Infinite Toki",
  "Toki infinita": "Infinite Toki",
  "Toki la Infinita": "Infinite Toki",
  "Toki l’Infinie": "Infinite Toki",
  "永恒者托奇": "Infinite Toki",
  "Toki die Unendliche": "Infinite Toki",
  "Toki dell'Infinito": "Infinite Toki",
  "Смотритель": "The Curator",
  "El Curator": "The Curator",
  "Le conservateur": "The Curator",
  "馆长": "The Curator",
  "Der Kurator": "The Curator",
  "Curatore": "The Curator",
  "Лоскутик": "Patchwerk",
  "Remendejo": "Patchwerk",
  "Le Recousu": "Patchwerk",
  "帕奇维克": "Patchwerk",
  "Flickwerk": "Patchwerk",
  "Pezzacarne": "Patchwerk",
  "Йогг-Сарон": "Yogg-Saron, Hope's End",
  "Yogg-Saron, Fin de la esperanza": "Yogg-Saron, Hope's End",
  "Yogg-Saron, Fin de la Esperanza": "Yogg-Saron, Hope's End",
  "Yogg-Saron, la fin de l’espoir": "Yogg-Saron, Hope's End",
  "尤格-萨隆": "Yogg-Saron, Hope's End",
  "Yogg-Saron, Hoffnungsende": "Yogg-Saron, Hope's End",
  "Yogg-Saron": "Yogg-Saron, Hope's End",
  "Танцор Дэрил": "Dancin' Deryl",
  "Daryl Danzarín": "Dancin' Deryl",
  "Daryl el Bailarín": "Dancin' Deryl",
  "Daryl le Danseur": "Dancin' Deryl",
  "舞者达瑞尔": "Dancin' Deryl",
  "Der steppende Steppke": "Dancin' Deryl",
  "Sfrl lo Sfrenato": "Dancin' Deryl",
  "Лорд Джараксус": "Lord Jaraxxus",
  "Lord Jaraxxus": "Lord Jaraxxus",
  "Seigneur Jaraxxus": "Lord Jaraxxus",
  "加拉克苏斯大王": "Lord Jaraxxus",
  "Sire Jaraxxus": "Lord Jaraxxus",
  "Король Мукла": "King Mukla",
  "Rey Mukla": "King Mukla",
  "Roi Mukla": "King Mukla",
  "穆克拉": "King Mukla",
  "König Mukla": "King Mukla",
  "Re Mukla": "King Mukla",
  "Пирамидон": "Pyramad",
  "Pyramad": "Pyramad",
  "Piramido": "Pyramad",
  "Pyraride": "Pyramad",
  "疯狂金字塔": "Pyramad",
  "Pyramidos": "Pyramad",
  "Piramatta": "Pyramad",
  "Сэр Финли Мрргглтон": "Sir Finley Mrrgglton",
  "Sir Aletardo Mrrgglton": "Sir Finley Mrrgglton",
  "Sir Finley Mrrgglton": "Sir Finley Mrrgglton",
  "芬利·莫格顿爵士": "Sir Finley Mrrgglton",
  "Ser Pinnus Mrrgglton": "Sir Finley Mrrgglton",
  "Рено Джексон": "Reno Jackson",
  "Reno Jackson": "Reno Jackson",
  "雷诺·杰克逊": "Reno Jackson",
  "Элиза Звездочет": "Elise Starseeker",
  "Elisa Buscaestelar": "Elise Starseeker",
  "Elise Buscaestelar": "Elise Starseeker",
  "Élise Cherchétoile": "Elise Starseeker",
  "伊莉斯·逐星": "Elise Starseeker",
  "Elise Sternensucher": "Elise Starseeker",
  "Elise Cercastelle": "Elise Starseeker",
  "Укротитель ящеров Бранн": "Dinotamer Brann",
  "Domadinos Brann": "Dinotamer Brann",
  "Dinodompteur Brann": "Dinotamer Brann",
  "恐龙大师布莱恩": "Dinotamer Brann",
  "Brann der Dinozähmer": "Dinotamer Brann",
  "Domasauri Brann": "Dinotamer Brann",
  "Суперзлодей Рафаам": "Arch-Villain Rafaam",
  "Archivillano Rafaam": "Arch-Villain Rafaam",
  "Prince du mal Rafaam": "Arch-Villain Rafaam",
  "至尊盗王拉法姆": "Arch-Villain Rafaam",
  "Erzschurke Rafaam": "Arch-Villain Rafaam",
  "Arcicattivo Rafaam": "Arch-Villain Rafaam",
  "Миллхаус Манашторм": "Millhouse Manastorm",
  "Molino Tormenta de Maná": "Millhouse Manastorm",
  "Millhouse Tempête-de-Mana": "Millhouse Manastorm",
  "米尔豪斯·法力风暴": "Millhouse Manastorm",
  "Millhaus Manasturm": "Millhouse Manastorm",
  "Millhouse Manalampo": "Millhouse Manastorm",
  "Тесс Седогрив": "Tess Greymane",
  "Tess Cringris": "Tess Greymane",
  "Tess Cringrís": "Tess Greymane",
  "Tess Grisetête": "Tess Greymane",
  "苔丝·格雷迈恩": "Tess Greymane",
  "Tess Graumähne": "Tess Greymane",
  "Tess Mantogrigio": "Tess Greymane",
  "Смертокрыл": "Deathwing",
  "Alamuerte": "Deathwing",
  "Aile de mort": "Deathwing",
  "死亡之翼": "Deathwing",
  "Todesschwinge": "Deathwing",
  "Alamorte": "Deathwing",
  "Изера": "Ysera",
  "Ysera": "Ysera",
  "伊瑟拉": "Ysera",
  "Грибомант Флургл": "Fungalmancer Flurgl",
  "Fungimántico Flurgl": "Fungalmancer Flurgl",
  "Fongimancien Flurgl": "Fungalmancer Flurgl",
  "菌菇术士弗洛格尔": "Fungalmancer Flurgl",
  "Fungumant Flrrgl": "Fungalmancer Flurgl",
  "Fungomante Flurgl": "Fungalmancer Flurgl",
  "Алекстраза": "Alexstrasza",
  "Alexstrasza": "Alexstrasza",
  "阿莱克丝塔萨": "Alexstrasza",
  "Ноздорму": "Nozdormu",
  "Nozdormu": "Nozdormu",
  "诺兹多姆": "Nozdormu",
  "Малигос": "Malygos",
  "Malygos": "Malygos",
  "玛里苟斯": "Malygos",
  "Аранна Звездочет": "Aranna Starseeker",
  "Aranna Buscaestelar": "Aranna Starseeker",
  "Aranna Cherchétoile": "Aranna Starseeker",
  "阿兰娜·逐星": "Aranna Starseeker",
  "Aranna Sternensucher": "Aranna Starseeker",
  "Aranna Cercastelle": "Aranna Starseeker",
  "Принц Кель'тас": "Kael'thas Sunstrider",
  "Kael'thas Caminante del Sol": "Kael'thas Sunstrider",
  "Kael’thas Haut-Soleil": "Kael'thas Sunstrider",
  "凯尔萨斯·逐日者": "Kael'thas Sunstrider",
  "Kael’thas Sonnenwanderer": "Kael'thas Sunstrider",
  "Kael'thas Solealto": "Kael'thas Sunstrider",
  "Майев Песнь Теней": "Maiev Shadowsong",
  "Maiev Cantosombrío": "Maiev Shadowsong",
  "Maiev Chantelombre": "Maiev Shadowsong",
  "玛维·影歌": "Maiev Shadowsong",
  "Maiev Schattensang": "Maiev Shadowsong",
  "Maiev Cantombroso": "Maiev Shadowsong",
  "Капитан Юдора": "Captain Eudora",
  "Capitana Eudora": "Captain Eudora",
  "Capitaine Eudora": "Captain Eudora",
  "尤朵拉船长": "Captain Eudora",
  "Käpt’n Eudora": "Captain Eudora",
  "Capitano Eudora": "Captain Eudora",
  "Капитан Кривоклык": "Captain Hooktusk",
  "Capitana Colmigarfio": "Captain Hooktusk",
  "Capitaine Double-Crochet": "Captain Hooktusk",
  "钩牙船长": "Captain Hooktusk",
  "Käpt’n Haizahn": "Captain Hooktusk",
  "Capitan Zannuncino": "Captain Hooktusk",
  "Крагг Поднебесный": "Skycap'n Kragg",
  "Capitán celestial Kragg": "Skycap'n Kragg",
  "Capitán de los cielos Kragg": "Skycap'n Kragg",
  "Cap’taine céleste Kragg": "Skycap'n Kragg",
  "天空上尉库拉格": "Skycap'n Kragg",
  "Himmelskäpt’n Kragg": "Skycap'n Kragg",
  "Gran Capitano Kragg": "Skycap'n Kragg",
  "Мистер Бигглсуорт": "Mr. Bigglesworth",
  "Baldomero": "Mr. Bigglesworth",
  "M. Bigglesworth": "Mr. Bigglesworth",
  "比格沃斯先生": "Mr. Bigglesworth",
  "Mr. Bigglesworth": "Mr. Bigglesworth",
  "Signor Bigolo": "Mr. Bigglesworth",
  "Джандис Барова": "Jandice Barov",
  "Jandice Barov": "Jandice Barov",
  "詹迪斯·巴罗夫": "Jandice Barov",
  "Лорд Баров": "Lord Barov",
  "Lord Barov": "Lord Barov",
  "Seigneur Barov": "Lord Barov",
  "巴罗夫领主": "Lord Barov",
  "Ser Barov": "Lord Barov",
  "Страж леса Ому": "Forest Warden Omu",
  "Guardiana del bosque Omu": "Forest Warden Omu",
  "Omu, celadora del bosque": "Forest Warden Omu",
  "Gardienne de la forêt Omu": "Forest Warden Omu",
  "林地守护者欧穆": "Forest Warden Omu",
  "Waldwächterin Omu": "Forest Warden Omu",
  "Guardiana Omu": "Forest Warden Omu",
  "Раканишу": "Rakanishu",
  "Rakanishu": "Rakanishu",
  "拉卡尼休": "Rakanishu",
  "Ал'акир": "Al'Akir",
  "Al'Akir": "Al'Akir",
  "Al’Akir": "Al'Akir",
  "奥拉基尔": "Al'Akir",
  "Нави'ла": "Chenvaala",
  "Chenvaala": "Chenvaala",
  "Chenvaa’la": "Chenvaala",
  "齐恩瓦拉": "Chenvaala",
  "Зефрис Великий": "Zephrys, the Great",
  "El Gran Zephrys": "Zephrys, the Great",
  "Zephrys el Grande": "Zephrys, the Great",
  "Zéphrys le Grand": "Zephrys, the Great",
  "了不起的杰弗里斯": "Zephrys, the Great",
  "Zephrys der Große": "Zephrys, the Great",
  "Zefris il Grande": "Zephrys, the Great",
  "Aranna, Unleashed": "Aranna Starseeker",
  "Аранна Освобожденная": "Aranna Starseeker",
  "Aranna, Desatada": "Aranna Starseeker",
  "Aranna desatada": "Aranna Starseeker",
  "Aranna, déchaînée": "Aranna Starseeker",
  "释放自我的阿兰娜": "Aranna Starseeker",
  "Aranna die Entfesselte": "Aranna Starseeker",
  "Aranna, Inarrestabile": "Aranna Starseeker",
};
export default hero_localize;
