// Build version: 65000
const minionType = {
    "Crowd Favorite": "NEUTRAL",
    "Nathrezim Overseer": "DEMON",
    "Soul Juggler": "NEUTRAL",
    "Wrath Weaver": "NEUTRAL",
    "Sneed's Old Shredder": "MECHANICAL",
    "Ghastcoiler": "BEAST",
    "Lightfang Enforcer": "NEUTRAL",
    "Annihilan Battlemaster": "DEMON",
    "Kangor's Apprentice": "NEUTRAL",
    "Imprisoner": "DEMON",
    "Pack Leader": "NEUTRAL",
    "Goldrinn, the Great Wolf": "BEAST",
    "Red Whelp": "DRAGON",
    "Primalfin Lookout": "MURLOC",
    "Mama Bear": "BEAST",
    "Zapp Slywick": "NEUTRAL",
    "Piloted Shredder": "MECHANICAL",
    "Micro Machine": "MECHANICAL",
    "Shifter Zerus": "NEUTRAL",
    "King Bagurgle": "MURLOC",
    "Herald of Flame": "DRAGON",
    "Hangry Dragon": "DRAGON",
    "Bronze Warden": "DRAGON",
    "Waxrider Togwaggle": "NEUTRAL",
    "Razorgore, the Untamed": "DRAGON",
    "Steward of Time": "DRAGON",
    "Twilight Emissary": "DRAGON",
    "Dragonspawn Lieutenant": "DRAGON",
    "Nadina the Red": "NEUTRAL",
    "Kalecgos, Arcane Aspect": "DRAGON",
    "Murozond": "DRAGON",
    "Imp Mama": "DEMON",
    "Glyph Guardian": "DRAGON",
    "Nat Pagle, Extreme Angler": "PIRATE",
    "Dread Admiral Eliza": "PIRATE",
    "Southsea Strongarm": "PIRATE",
    "Freedealing Gambler": "PIRATE",
    "Bloodsail Cannoneer": "PIRATE",
    "Deck Swabbie": "PIRATE",
    "Ripsnarl Captain": "PIRATE",
    "Yo-Ho-Ogre": "PIRATE",
    "Scallywag": "PIRATE",
    "Goldgrubber": "PIRATE",
    "Drakonid Enforcer": "DRAGON",
    "Amalgadon": "ALL",
    "Deflect-o-Bot": "MECHANICAL",
    "Cap'n Hoggarr": "PIRATE",
    "Rabid Saurolisk": "BEAST",
    "Monstrous Macaw": "BEAST",
    "The Tide Razor": "NEUTRAL",
    "Seabreaker Goliath": "PIRATE",
    "Salty Looter": "PIRATE",
    "Menagerie Mug": "NEUTRAL",
    "Menagerie Jug": "NEUTRAL",
    "Lil' Rag": "ELEMENTAL",
    "Nomi, Kitchen Nightmare": "NEUTRAL",
    "Majordomo Executus": "NEUTRAL",
    "Sellemental": "ELEMENTAL",
    "Refreshing Anomaly": "ELEMENTAL",
    "Crackling Cyclone": "ELEMENTAL",
    "Party Elemental": "ELEMENTAL",
    "Gentle Djinni": "ELEMENTAL",
    "Stasis Elemental": "ELEMENTAL",
    "Tavern Tempest": "ELEMENTAL",
    "Lieutenant Garr": "ELEMENTAL",
    "Wildfire Elemental": "ELEMENTAL",
    "Molten Rock": "ELEMENTAL",
    "Arcane Assistant": "ELEMENTAL",
    "Deadly Spore": "NEUTRAL",
    "Security Rover": "MECHANICAL",
    "Replicating Menace": "MECHANICAL",
    "Mechano-Egg": "MECHANICAL",
    "Kaboom Bot": "MECHANICAL",
    "Annoy-o-Module": "MECHANICAL",
    "Imp Gang Boss": "DEMON",
    "Felfin Navigator": "MURLOC",
    "Alleycat": "BEAST",
    "Rat Pack": "BEAST",
    "Crystalweaver": "NEUTRAL",
    "Virmen Sensei": "NEUTRAL",
    "Toxfin": "MURLOC",
    "Khadgar": "NEUTRAL",
    "Houndmaster": "NEUTRAL",
    "Old Murk-Eye": "MURLOC",
    "Defender of Argus": "NEUTRAL",
    "Coldlight Seer": "MURLOC",
    "Siegebreaker": "DEMON",
    "Murloc Tidehunter": "MURLOC",
    "Murloc Warleader": "MURLOC",
    "Murloc Tidecaller": "MURLOC",
    "Scavenging Hyena": "BEAST",
    "Savannah Highmane": "BEAST",
    "Harvest Golem": "MECHANICAL",
    "The Beast": "BEAST",
    "Maexxna": "BEAST",
    "Unstable Ghoul": "NEUTRAL",
    "Baron Rivendare": "NEUTRAL",
    "Mal'Ganis": "DEMON",
    "Iron Sensei": "MECHANICAL",
    "Metaltooth Leaper": "MECHANICAL",
    "Screwjank Clunker": "MECHANICAL",
    "Floating Watcher": "DEMON",
    "Junkbot": "MECHANICAL",
    "Foe Reaper 4000": "MECHANICAL",
    "Cobalt Scalebane": "DRAGON",
    "Righteous Protector": "NEUTRAL",
    "Strongshell Scavenger": "NEUTRAL",
    "Bolvar, Fireblood": "NEUTRAL",
    "Kindly Grandmother": "BEAST",
    "Brann Bronzebeard": "NEUTRAL",
    "Vulgar Homunculus": "DEMON",
    "Cave Hydra": "BEAST",
    "Voidlord": "DEMON",
    "Southsea Captain": "PIRATE",
    "Infested Wolf": "BEAST",
    "Selfless Hero": "NEUTRAL",
    "Spawn of N'Zoth": "NEUTRAL",
    "Ironhide Direhorn": "BEAST",
    "Micro Mummy": "MECHANICAL",
    "Rockpool Hunter": "MURLOC",
    "Fiendish Servant": "DEMON",
};
export default minionType;
