// Build version: 138759
const minionType = {
    "Sewer Rat": "BEAST",
    "Razorfen Geomancer": "QUILBOAR",
    "Roadboar": "QUILBOAR",
    "Tough Tusk": "QUILBOAR",
    "Bristleback Brute": "QUILBOAR",
    "Bonker": "QUILBOAR",
    "Thorncaller": "QUILBOAR",
    "Groundshaker": "QUILBOAR",
    "Bannerboar": "QUILBOAR",
    "Necrolyte": "QUILBOAR",
    "Prophet of the Boar": "NEUTRAL",
    "Bristleback Knight": "QUILBOAR",
    "Agamaggan, the Great Boar": "BEAST",
    "Dynamic Duo": "QUILBOAR",
    "Sun-Bacon Relaxer": "QUILBOAR",
    "Aggem Thorncurse": "QUILBOAR",
    "Charlga": "QUILBOAR",
    "Holy Mecherel": "MECHANICAL",
    "Leapfrogger": "BEAST",
    "Palescale Crocolisk": "BEAST",
    "Bird Buddy": "NEUTRAL",
    "Reanimating Rattler": "BEAST",
    "Insatiable Ur'zul": "DEMON",
    "Famished Felbat": "DEMON",
    "Impulsive Trickster": "DEMON",
    "Impatient Doomsayer": "NEUTRAL",
    "Saltscale Honcho": "MURLOC",
    "SI:Sefin": "MURLOC",
    "Swolefin": "MURLOC",
    "Prestor's Pyrospawn": "DRAGON",
    "Whelp Smuggler": "NEUTRAL",
    "Prized Promo-Drake": "DRAGON",
    "Tarecgosa": "DRAGON",
    "Peggy Brittlebone": "PIRATE",
    "Briny Bootlegger": "PIRATE",
    "Nosy Looter": "PIRATE",
    "Dazzling Lightspawn": "ELEMENTAL",
    "Smogger": "ELEMENTAL",
    "Pupbot": "MECHANICAL",
    "Mechano-Tank": "MECHANICAL",
    "Grease Bot": "MECHANICAL",
    "Omega Buster": "MECHANICAL",
    "Evolving Chromawing": "DRAGON",
    "Icky Imp": "DEMON",
    "Budding Greenthumb": "NEUTRAL",
    "Tony Two-Tusk": "PIRATE",
    "Master of Realities": "NEUTRAL",
    "Gemsplitter": "QUILBOAR",
    "Witchwing Nestmatron": "NEUTRAL",
    "Kathra'natir": "DEMON",
    "Recycling Wraith": "ELEMENTAL",
    "Baby Krush": "BEAST",
    "Tad": "MURLOC",
    "Swampstriker": "MURLOC",
    "Mantid Queen": "NEUTRAL",
    "Young Murk-Eye": "MURLOC",
    "Mini-Myrmidon": "NAGA",
    "Snail Cavalry": "NAGA",
    "Shell Collector": "NAGA",
    "Critter Wrangler": "NAGA",
    "Deep-Sea Angler": "NAGA",
    "Stormscale Siren": "NAGA",
    "Eelbound Archer": "NAGA",
    "Waverider": "NAGA",
    "Glowscale": "NAGA",
    "Lava Lurker": "NAGA",
    "Eventide Brute": "NAGA",
    "Shoal Commander": "NAGA",
    "Corrupted Myrmidon": "NAGA",
    "Tidemistress Athissa": "NAGA",
    "Pashmar the Vengeful": "NAGA",
    "Orgozoa, the Tender": "NEUTRAL",
    "Reef Explorer": "NEUTRAL",
    "Darkgaze Elder": "QUILBOAR",
    "Leeroy the Reckless": "NEUTRAL",
    "Nathrezim Overseer": "DEMON",
    "Soul Juggler": "NEUTRAL",
    "Wrath Weaver": "NEUTRAL",
    "Ghastcoiler": "BEAST",
    "Lightfang Enforcer": "NEUTRAL",
    "Annihilan Battlemaster": "DEMON",
    "Kangor's Apprentice": "NEUTRAL",
    "Imprisoner": "DEMON",
    "Goldrinn, the Great Wolf": "BEAST",
    "Red Whelp": "DRAGON",
    "Primalfin Lookout": "MURLOC",
    "Mama Bear": "BEAST",
    "Zapp Slywick": "NEUTRAL",
    "King Bagurgle": "MURLOC",
    "Bronze Warden": "DRAGON",
    "Razorgore, the Untamed": "DRAGON",
    "Twilight Emissary": "DRAGON",
    "Nadina the Red": "NEUTRAL",
    "Kalecgos, Arcane Aspect": "DRAGON",
    "Murozond": "DRAGON",
    "Imp Mama": "DEMON",
    "Glyph Guardian": "DRAGON",
    "Dread Admiral Eliza": "PIRATE",
    "Southsea Strongarm": "PIRATE",
    "Freedealing Gambler": "PIRATE",
    "Deck Swabbie": "PIRATE",
    "Ripsnarl Captain": "PIRATE",
    "Soul Devourer": "DEMON",
    "Yo-Ho-Ogre": "PIRATE",
    "Scallywag": "PIRATE",
    "Goldgrubber": "PIRATE",
    "Drakonid Enforcer": "DRAGON",
    "Deflect-o-Bot": "MECHANICAL",
    "Cap'n Hoggarr": "PIRATE",
    "Rabid Saurolisk": "BEAST",
    "Monstrous Macaw": "BEAST",
    "Salty Looter": "PIRATE",
    "Menagerie Mug": "NEUTRAL",
    "Menagerie Jug": "NEUTRAL",
    "Lil' Rag": "ELEMENTAL",
    "Nomi, Kitchen Nightmare": "NEUTRAL",
    "Majordomo Executus": "NEUTRAL",
    "Acolyte of C'Thun": "NEUTRAL",
    "Arm of the Empire": "NEUTRAL",
    "Sellemental": "ELEMENTAL",
    "Refreshing Anomaly": "ELEMENTAL",
    "Crackling Cyclone": "ELEMENTAL",
    "Party Elemental": "ELEMENTAL",
    "Gentle Djinni": "ELEMENTAL",
    "Stasis Elemental": "ELEMENTAL",
    "Tavern Tempest": "ELEMENTAL",
    "Wildfire Elemental": "ELEMENTAL",
    "Molten Rock": "ELEMENTAL",
    "Mythrax the Unraveler": "NEUTRAL",
    "Bigfernal": "DEMON",
    "Replicating Menace": "MECHANICAL",
    "Mechano-Egg": "MECHANICAL",
    "Kaboom Bot": "MECHANICAL",
    "Annoy-o-Module": "MECHANICAL",
    "Felfin Navigator": "MURLOC",
    "Alleycat": "BEAST",
    "Rat Pack": "BEAST",
    "Khadgar": "NEUTRAL",
    "Ring Matron": "DEMON",
    "Houndmaster": "NEUTRAL",
    "Defender of Argus": "NEUTRAL",
    "Coldlight Seer": "MURLOC",
    "Murloc Warleader": "MURLOC",
    "Scavenging Hyena": "BEAST",
    "Savannah Highmane": "BEAST",
    "Harvest Golem": "MECHANICAL",
    "Unstable Ghoul": "NEUTRAL",
    "Baron Rivendare": "NEUTRAL",
    "Nightmare Amalgam": "ALL",
    "Metaltooth Leaper": "MECHANICAL",
    "Screwjank Clunker": "MECHANICAL",
    "Foe Reaper 4000": "MECHANICAL",
    "Cobalt Scalebane": "DRAGON",
    "Strongshell Scavenger": "NEUTRAL",
    "Brann Bronzebeard": "NEUTRAL",
    "Cave Hydra": "BEAST",
    "Voidlord": "DEMON",
    "Southsea Captain": "PIRATE",
    "Selfless Hero": "NEUTRAL",
    "Spawn of N'Zoth": "NEUTRAL",
    "Micro Mummy": "MECHANICAL",
    "Rockpool Hunter": "MURLOC",
};
export default minionType;
